; PlatformIO project config for M5Atom_WPS
; Build: pio run
; Upload: pio run -t upload

[platformio]
src_dir = .

[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter =
    +<*.ino>
    +<*.cpp>
lib_deps =
    symlink://../..
    m5stack/M5Unified @ ^0.2.5
